In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import load_iris

In [3]:
data = load_iris()

In [4]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

In [7]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [8]:
df.target.unique()

array([0, 1, 2])

In [9]:
df.target.value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

In [10]:
df.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [11]:
X = df.iloc[:, :-1]
y = df.iloc[:,-1]

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [13]:
X_train.shape, X_test.shape

((120, 4), (30, 4))

In [14]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=300)
model

LogisticRegression(max_iter=300)

In [15]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=300)

In [16]:
y_pred = model.predict(X_test)

In [17]:
y_pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2])

In [18]:
model.predict_proba(X_test)

array([[9.84756689e-01, 1.52432895e-02, 2.17403380e-08],
       [2.75843867e-01, 7.21507577e-01, 2.64855587e-03],
       [6.26205833e-03, 8.89221293e-01, 1.04516649e-01],
       [9.85522198e-01, 1.44777388e-02, 6.33208938e-08],
       [1.17348581e-06, 1.90302000e-02, 9.80968627e-01],
       [4.50573045e-03, 6.27836120e-01, 3.67658150e-01],
       [1.46175646e-04, 1.27770370e-01, 8.72083455e-01],
       [9.57839634e-01, 4.21591383e-02, 1.22786546e-06],
       [9.69638820e-01, 3.03608711e-02, 3.08667081e-07],
       [9.68996985e-06, 2.70719120e-02, 9.72918398e-01],
       [1.89399294e-02, 8.79769422e-01, 1.01290649e-01],
       [9.66510269e-01, 3.34892888e-02, 4.42337597e-07],
       [4.69365029e-06, 3.10311243e-02, 9.68964182e-01],
       [7.11956580e-03, 8.01827403e-01, 1.91053032e-01],
       [6.95461428e-03, 7.49175383e-01, 2.43870003e-01],
       [9.88135891e-01, 1.18640415e-02, 6.70262587e-08],
       [2.24708082e-02, 9.37026697e-01, 4.05024947e-02],
       [1.09173809e-02, 6.81846

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [20]:
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        13
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

